### PR TITLE
Update icon and language name

### PR DESCRIPTION
**Pull request by efast1568**
I don't want to bring up sensitive political issues on the forum.
However, traditional chinese is not actually used in China, only in  freedom Taiwan and other regions. Can the flags/icon 
 of the  language packs be replaced or canceled? Maybe do it quietly.

### CODE REVIEW

**Comment by rob006** [comment]
Flarum uses square icons for extensions, including language pack, so square icon would be better. Is bellow icon OK as flag for this language pack?

**Comment by efast1568** [comment]
For me any style is better than the old one, thanks for understanding

**Comment by rob006** [comment]
Merged, thanks for clarifying this!

**Comment by rob006** [comment]
@efast1568 Could you also take a look at dayjs translations? Currently I used general Chinese translation: https://github.com/iamkun/dayjs/blob/v1.11.6/src/locale/zh.js

But there are also regionalized translations for:
1. Taiwan https://github.com/iamkun/dayjs/blob/v1.11.6/src/locale/zh-tw.js
2. Hong Kong: https://github.com/iamkun/dayjs/blob/v1.11.6/src/locale/zh-hk.js

Could you help picking up the best translation for dayjs?

**Comment by efast1568** [comment]
> @efast1568 Could you also take a look at dayjs translations? Currently I used general Chinese translation: https://github.com/iamkun/dayjs/blob/v1.11.6/src/locale/zh.js
> 
> But there are also regionalized translations for:
> 
> 1. Taiwan https://github.com/iamkun/dayjs/blob/v1.11.6/src/locale/zh-tw.js
> 2. Hong Kong: https://github.com/iamkun/dayjs/blob/v1.11.6/src/locale/zh-hk.js
> 
> Could you help picking up the best translation for dayjs?

Thank you for your carefulness, it is indeed necessary to use zh-tw.js Its content is the same as zh-hk

**Comment by rob006** [comment]
Fixed in https://github.com/flarum-lang/chinese-traditional/commit/560b7895a52191704e486a2e4c8e6ba9ad6d3d55

**Pull request merged**
