### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by efast1568**
Extension title fix

### CODE REVIEW

**Comment by rob006** [comment]
I don't think this change is correct. Values in `keywords` are key used as keywords at https://packagist.org/, and almost all of them are in English. I don't think that having Chinese keywords here would be useful, since this is not common convention.

As for `flarum-extension.title` - this value is displayed in admin panel only, and it is good to keep it in English, since almost all other extensions follow this convention, including most of language packs. It is also more convenient for admins - if you have multilingual forum, you may want to use this language pack even if you don speak Chinese. If you translate extension name, it may be harder to understand what this extension is about.

**Comment by efast1568** [comment]
> I don't think this change is correct. Values in `keywords` are key used as keywords at https://packagist.org/, and almost all of them are in English. I don't think that having Chinese keywords here would be useful, since this is not common convention.
> 
> As for `flarum-extension.title` - this value is displayed in admin panel only, and it is good to keep it in English, since almost all other extensions follow this convention, including most of language packs. It is also more convenient for admins - if you have multilingual forum, you may want to use this language pack even if you don speak Chinese. If you translate extension name, it may be harder to understand what this extension is about.

I agree with your definition of the extension title, so that the maintainer can manage it conveniently. 

But I think keywords is helpful, especially for people who don't understand English, it really helps to search for extensions.
Screenshot_20221128_074343_Samsung Internet

**Comment by rob006** [comment]
> But I think keywords is helpful, especially for people who don't understand English, it really helps to search for extensions.

If someone does not understand English, he may have problems with using https://packagist.org/ in general, since the whole website is in English. Packagist is also a pretty bad tool if you search for language packs, since results are flooded by outdated or abandoned extensions.

I think we need something like "awesome language pack for Flarum" with curated lists of language packs so it would be easier to find actively maintained language pack for your forum. We could include keywords/localization there.

**Comment by efast1568** [comment]
I agree with your comment.
Thank you for understanding the cultural differences between Traditional and Simplified Chinese, and for generously supporting the flag change request.
I think I'm done with the translation requests currently on weblate.
Not very precise, but should be OK.
I might check monthly to make sure it's as complete as possible.

**Comment by efast1568** [comment]
> 



> I think we need something like "awesome language pack for Flarum" with curated lists of language packs so it would be easier to find actively maintained language pack for your forum. We could include keywords/localization there.

I agree with your comment.
Thank you for understanding the cultural differences between Traditional and Simplified Chinese, and for generously supporting the flag change request.
I think I'm done with the translation requests currently on weblate.
Not very precise, but should be OK.
I might check monthly to make sure it's as complete as possible.

**Comment by GreXXL** [comment]
> I think we need something like "awesome language pack for Flarum" with curated lists of language packs so it would be easier to find actively maintained language pack for your forum. We could include keywords/localization there.

There actually is a good way to get an overview about all language packs available for Flarum at Extiverse: https://extiverse.com/?filter%5Bq%5D=&sort=-created_at&filter%5Bis%5D%5B%5D=-flarum&filter%5Btype%5D=locale

**Comment by rob006** [comment]
> There actually is a good way to get an overview about all language packs available for Flarum at Extiverse

It is pretty bad. I would even say that it is worse than Packagist - it not only includes outdated packs and forks, but it also hides some maintained language packs (for example both Chinese packs from flarum-lang are hidden for some reason).
I would keep it in mind and maybe prepare some list/repo after completing https://github.com/rob006-software/flarum-translations/issues/977

@efast1568 I released `v1.0.0` in https://github.com/flarum-lang/chinese-traditional/pull/1. I also granted you maintainer permissions on Weblate in GitHub (you need to accept invite). In future you should be able to tag new releases in new PRs similar to https://github.com/flarum-lang/chinese-traditional/pull/1 - just make sure that your read instructions in first comment, there is a link to guide how to approve PR.

**Pull request closed without merging**
